### ISSUE TITLE
pipy package

### ISSUE THREAD

**Issue by pix106** [python-cas/python-cas#11]
Hi,
i installed python-cas from pypi, it lacks lxml dependency.
If i install from github,  lxml dependency is satisfied, due to a commit that is more recent than the latest pypi release (1.2.0)
Would you please release an update on pypi so this dependency is satisfied ?
Thanks :)

**Comment by bermudezjd** [comment]
I agree with the above.  I think a release is long overdue for this project - doing so would alleviate the missing lxml dependency (needed by `django-cas-ng`).

**Comment by jdufresne** [comment]
Looks like a new version was released on Oct 9, 2018. I think this can be closed.
