### ISSUE TITLE
Add debug logging, will submit pull request

### ISSUE THREAD

**Issue by danizen** [python-cas/python-cas#13]
Just some minor stuff to see the verify ticket response in a debug log.   Login/logout should not be so frequent that logger.debug(...) is significant to performance.

I'm a contributor to django-cas-ng and responsible for maintaining a package used within the U.S. National Library of Medicine that enables CAS login through a server that allows logins by NIH Staff, sometimes users from Google, etc.

**Comment by mingchen** [comment]
PR is always welcome.

**Comment by mingchen** [comment]
closed due to inactive.
