### ISSUE TITLE
Kwarg to bypass SSL certificate validation

### ISSUE THREAD

**Issue by duoi** [python-cas/python-cas#15]
**The situation:** 

Local development, especially in teams, means that me or my team might generate unsigned certificates when testing my CAS server.

**A solution**

Add a kwarg `verify_ssl_certificate` to `CASClientBase` with a default of `True`. `verify_ssl_certificate` is passed into `requests.get()` calls, as the value for the `verify` kwarg.

**Comment by mingchen** [comment]
Fixed by PR #16
